### ISSUE TITLE
Have a printable version of the site

### ISSUE THREAD

**Issue by enamakel** [enamakel/kuwait-and-me#3]
We need to make use of CSS's print media type. An example is the code below which gets rid of the header in the print-out version of the page.

```css
@media print {
    header {
        display: none
    }
}
```

It's a pity many websites (even well recognized ones) don't have a printable version of their site. It's seems like a nice feature to have since it lets people print out classifieds that they are interested in.
